### ISSUE TITLE
pypy builds using pip and libraries not found?

### ISSUE THREAD

**Issue by ngam** [conda-forge/pypy-meta-feedstock#21]
xref: https://github.com/conda-forge/vowpalwabbit-feedstock/pull/44 and https://github.com/conda-forge/vowpalwabbit-feedstock/pull/45

Hi, in the vowpalwabbit feedstock, https://github.com/conda-forge/vowpalwabbit-feedstock, I believe we have an issue to do with pypy builds. The issue, it seems, that when building via pip, a pypy exe cannot find the associated libraries:

```
$ conda create -n test_pypy_old pypy vowpalwabbit==8.11.0
$ conda activate test_pypy_old
$ python -c "import vowpalwabbit; import vowpalwabbit.pyvw"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old/site-packages/vowpalwabbit/pyvw.py", line 5, in <module>
    import pylibvw
ModuleNotFoundError: No module named 'pylibvw'
```

while on the other hand, a regular python exe can:

```
$ conda create -n test_python_old python=3.7 vowpalwabbit==8.11.0
$ conda activate test_python_old
$ python -c "import vowpalwabbit; import vowpalwabbit.pyvw"
```

In both cases, the file structure (inside site-packages) seems identical. Maybe the issue can be tracked to importing a library named `pylibvw.so`, which is available right under `/site-packages/` in both cases. However, in the python environment, it is found, but in the pypy environment, it is not.

Could you please advise? I have disabled the pypi builds for now while we investigate. Thanks! 

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
(test_pypy_old) ngam@mp15:~$ conda list
# packages in environment at /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old:
#
# Name                    Version                   Build  Channel
boost                     1.74.0           py37h0122645_5    conda-forge
boost-cpp                 1.74.0               hf3dc895_5    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
expat                     2.4.3                he49afe7_0    conda-forge
gdbm                      1.18                 h8a0c380_2    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
numpy                     1.21.5           py37h810bc2a_0    conda-forge
openssl                   3.0.0                h0d85af4_2    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pypy                      7.3.7                  0_pypy37    conda-forge
pypy3.7                   7.3.7                h89ff3dc_3    conda-forge
python                    3.7.12                0_73_pypy    conda-forge
python_abi                3.7               2_pypy37_pp73    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                60.5.0           py37h5186d4c_0    conda-forge
sqlite                    3.37.0               h23a322b_0    conda-forge
tk                        8.6.11               h5dbffcc_1    conda-forge
vowpalwabbit              8.11.0           py37h9d266b7_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```

```
(test_python_old) ngam@mp15:~$ conda list
# packages in environment at /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_python_old:
#
# Name                    Version                   Build  Channel
boost                     1.74.0           py37h326c9ff_5    conda-forge
boost-cpp                 1.74.0               hf3dc895_5    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
numpy                     1.21.5           py37h3c8089f_0    conda-forge
openssl                   3.0.0                h0d85af4_2    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
python                    3.7.12          hf3644f1_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                60.5.0           py37hf985489_0    conda-forge
sqlite                    3.37.0               h23a322b_0    conda-forge
tk                        8.6.11               h5dbffcc_1    conda-forge
vowpalwabbit              8.11.0           py37hd6556a3_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
(test_pypy_old) ngam@mp15:~$ conda info 

     active environment : test_pypy_old
    active env location : /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_pypy_old
            shell level : 1
       user config file : /Users/ngam/.condarc
 populated config files : /Users/ngam/.Mambaforge-MacOSX-x86_64/.condarc
                          /Users/ngam/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.7
         python version : 3.9.9.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/ngam/.Mambaforge-MacOSX-x86_64  (writable)
      conda av data dir : /Users/ngam/.Mambaforge-MacOSX-x86_64/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/ngam/.Mambaforge-MacOSX-x86_64/pkgs
                          /Users/ngam/.conda/pkgs
       envs directories : /Users/ngam/.Mambaforge-MacOSX-x86_64/envs
                          /Users/ngam/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.9 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

```                        
(test_python_old) ngam@mp15:~$ conda info                    

     active environment : test_python_old
    active env location : /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/test_python_old
            shell level : 2
       user config file : /Users/ngam/.condarc
 populated config files : /Users/ngam/.Mambaforge-MacOSX-x86_64/.condarc
                          /Users/ngam/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.7
         python version : 3.9.9.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/ngam/.Mambaforge-MacOSX-x86_64  (writable)
      conda av data dir : /Users/ngam/.Mambaforge-MacOSX-x86_64/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/ngam/.Mambaforge-MacOSX-x86_64/pkgs
                          /Users/ngam/.conda/pkgs
       envs directories : /Users/ngam/.Mambaforge-MacOSX-x86_64/envs
                          /Users/ngam/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.9 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by ngam** [comment]
(Note: same results on linux64)

**Comment by isuruf** [comment]
`pylibvw.so` has the extension `.so` and it is only importable by `cpython`. PyPy requires a different extension given by `import sysconfig;print(sysconfig.get_config_vars("EXT_SUFFIX"))`

**Comment by ngam** [comment]
Confirmed. A simple manual symlink fixes this. Is this something we could perhaps institute system-wide? I assume this would come often?

Also, is there a quick way to add a symlink in the build script after this?

```
script: {{ PYTHON }} -m pip install . -vv
```

**Comment by isuruf** [comment]
It's better to fix with a patch to https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/CMakeLists.txt#L53

**Comment by ngam** [comment]
Thanks isuruf, closing this for now
